= i18n_icu
Rizzen Yazston
:icu4x: https://github.com/unicode-org/icu4x
:url-unicode: https://home.unicode.org/
:DataProvider: https://docs.rs/icu_provider/1.2.0/icu_provider/trait.DataProvider.html

{icu4x}[*ICU4X*] project (maintained by the {url-unicode}[*Unicode Consortium*]) data provider helper.

The `IcuDataProvider` type contains a member `data_provider` holding the ICU4X `&{DataProvider}[DataProvider]` as a `DataProviderWrapper` type.

The `IcuDataProvider` type also contains non-locale based data used within the `i18n_lexer` crate.

`IcuDataProvider` type is used within the `Rc` type as `Rc<IcuDataProvider>` to prevent unnecessary duplication. 

== Acknowledgement

Stefano Angeleri for advice on various design aspects of implementing the components of the internationalisation project, and also providing the Italian translation of error message strings.

== Cargo.toml

```
[dependencies]
icu_provider = "1.1.0"

# These are required for the DataProvider.
icu_properties = "1.1.0"
icu_segmenter = "0.8.0"
icu_plurals = "1.1.0"
icu_decimal = "1.1.0"
icu_calendar = "1.1.0"
icu_datetime = "1.1.0"

# This is required for the DataProvider.
[dependencies.fixed_decimal]
version = "0.5.2"
# Needed for floating point support.
features = [ "ryu" ]
```

== Examples

See various examples of the `i18n_lexer`, `i18n_pattern`, and `i18n_message` crates.
