# This file is part of `rust-i18n` project. For the terms of use, please see the file
# called `LICENSE-BSD-3-Clause` at the top level of the `rust-i18n` project's Git repository.

[workspace]
resolver = "2"
members = [
    "crates/lstring",
    "crates/error",
    "crates/lexer",
    "crates/pattern",
    "crates/provider/core",
    "crates/provider/sqlite3",
#    "crates/message",
    "crates/utility",
]

exclude = [
    # Currently no exclusions.
]
