# This file is part of `i18n` project. For the terms of use, please see the file
# called `LICENSE-BSD-3-Clause` at the top level of the `i18n` project's Git repository.

[workspace]
resolver = "2"
members = [
    "crates/lstring",
#    "crates/pattern",
#    "crates/message",
    "crates/utility",
]

exclude = [
    # Currently no exclusions.
]
